Project setup
AbuRayhaan/Viable-Project pull request #1
Opened 2022-04-09 14:41 UTC by AbuRayhaan

##Viable-Project: Project Setup

In this milestone, I did the following:
- Added linters file for `html-css-js` files.
- Added the `index.html` file.
- Added the `style.css` file.
- Added the `script.js` file.

2022-04-13 10:16 UTC, Kingstalux reviewed
Hi @AbuRayhaan, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f644550476b6e5269456e6965632f67697068792e676966](https://user-images.githubusercontent.com/85113567/163156721-72eabec8-2eea-46d4-8f96-fd85c45dd9ef.gif)


## Invalid Code Review Request 🛑 

- [ ] Kindly add a link to the video presentation of your capstone project which should have a maximum length of 5 minutes where you present all the features of your project and talk about a piece of interesting code you worked on 👍 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-04-13 16:27 UTC, ShoiraTa requested changes
Hi @AbuRayhaan ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-13 16:27 UTC, ShoiraTa commented on index.html
> +            </div>
- [ ] Please make sure that the logo is a link. Users should be able to click on logo and get to homepage.

2022-04-13 16:27 UTC, ShoiraTa commented on index.html
> +                <li class="header-white-menu-item"><a href="#about">About</a></li>
- [ ] When I click on `About` link, a new page should open with a `footer` and its own `navbar`, but instead I am taken to the different section of the same page with `#about` id. I noticed that in project you have only 1 html index file. Please kindly add `about.html` file as well and make sure that the About link takes to `about.html` page. 
- [ ] While writing `about.html` please try to stick  to provided [design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

2022-04-13 16:27 UTC, ShoiraTa commented on index.html
> +                with people from over 80 countries is taking place in Nigeria.
- [ ]  Based on project requirements it is necessary to use font families `Cocogoose, Lato`  as provided in the theme:
<img width="1045" alt="Screenshot 2022-04-13 at 17 45 41" src="https://user-images.githubusercontent.com/77038610/163194544-10e000d2-c657-4017-9205-5b11253cc1d8.png">

2022-04-13 16:27 UTC, ShoiraTa commented on index.html
> +            <h1 class="main-program">Main Program</h1>
- [ ] Kindly set the same height for the cards of this section: 
<img width="772" alt="Screenshot 2022-04-13 at 20 17 32" src="https://user-images.githubusercontent.com/77038610/163225166-14548638-7114-4691-a070-93be78312022.png">

2022-04-13 16:27 UTC, ShoiraTa commented on index.html
> +        </footer>
- [ ] Please make sure that footer contains a logo aligned to the left and text aligned to the right. Currently I can only see centred text: 
<img width="408" alt="Screenshot 2022-04-13 at 20 21 30" src="https://user-images.githubusercontent.com/77038610/163225842-7ee8f21b-3995-4b1f-a58c-e6d81a17ec31.png">

2022-04-13 16:27 UTC, ShoiraTa commented on README.md
> +
- [ ] Please update this section with current project links

2022-04-13 16:27 UTC, ShoiraTa commented on README.md
> +This project is [MIT](./MIT.md)
- [ ] License link is broken, kindly add `MIT` License file  to root directory to make the link work

2022-04-14 22:00 UTC, alexander16108 reviewed
Hi @AbuRayhaan , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/YRK4wOxia64Hi3xMXU/giphy.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-15 08:52 UTC, merged